# -----------------------------------------------------------------------------
# Services.
# -----------------------------------------------------------------------------

PartidoServiceFactory.className=es.udc.ws.app.model.PartidoService.PartidoServiceImpl

# -----------------------------------------------------------------------------
# SqlDaos.
# -----------------------------------------------------------------------------

SqlPartidoDaoFactory.className=es.udc.ws.app.model.Partido.Jdbc3CcSqlPartidoDao

SqlCompraEntradaDaoFactory.className=es.udc.ws.app.model.CompraEntrada.Jdbc3CcSqlCompraEntradaDao

